SHORT_STRING = 50
LONG_STRING = 255

RESULT_SUPPORTED = "1"
RESULT_NOT_SUPPORTED = "2"
RESULT_NOT_ANSWERED = None

RESULT_TYPE = (
    (RESULT_SUPPORTED, "Supported"),
    (RESULT_NOT_SUPPORTED, "Not Supported"),
)

TESTSUITE_TYPE_DEFAULT = "1"
TESTSUITE_TYPE_ACCESSIBILITY = "2"
TESTSUITE_TYPE = (
    (TESTSUITE_TYPE_DEFAULT, "default"),
    (TESTSUITE_TYPE_ACCESSIBILITY, "accessibility"),
)

INPUT_TYPE_KEYBOARD = "1"
INPUT_TYPE_MOUSE = "2"
INPUT_TYPE_TOUCH = "3"
INPUT_TYPE = (
    (INPUT_TYPE_KEYBOARD, "Keyboard"),
    (INPUT_TYPE_MOUSE, "Mouse"),
    (INPUT_TYPE_TOUCH, "Touch/Gestures"),
)

