# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 02:14
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'abstract': False,
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ATMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistive_technology', models.CharField(blank=True, max_length=255, null=True)),
                ('input_type', models.CharField(choices=[('1', 'Keyboard'), ('2', 'Mouse'), ('3', 'Touch/Gestures')], default='1', max_length=1)),
                ('supports_screenreader', models.BooleanField(default=False)),
                ('supports_braille', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('category_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Epub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epubid', models.TextField()),
                ('description', models.TextField()),
                ('title', models.TextField()),
                ('filename', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_complete', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_updated', models.DateTimeField()),
                ('is_archived', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_id', models.TextField()),
                ('name', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsuite_app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
                ('operating_system', models.CharField(max_length=50)),
                ('operating_system_version', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(blank=True, choices=[('1', 'Supported'), ('2', 'Not Supported')], max_length=1, null=True)),
                ('notes', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(300)])),
                ('publish_notes', models.BooleanField(default=False)),
                ('flagged', models.BooleanField(default=False)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsuite_app.Evaluation')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fraction', models.CharField(max_length=50)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsuite_app.Evaluation')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('required', models.BooleanField()),
                ('test_id', models.CharField(max_length=50)),
                ('xhtml', models.TextField()),
                ('order_in_book', models.IntegerField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testsuite_app.Category')),
                ('epub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsuite_app.Epub')),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testsuite_app.Feature')),
            ],
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_date', models.DateTimeField(max_length=50)),
                ('testsuite_type', models.CharField(choices=[('1', 'default'), ('2', 'accessibility')], default='1', max_length=1)),
                ('allow_many_evaluations', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('testsuite_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='testsuite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsuite_app.TestSuite'),
        ),
        migrations.AddField(
            model_name='result',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsuite_app.Test'),
        ),
        migrations.AddField(
            model_name='feature',
            name='testsuite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsuite_app.TestSuite'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='reading_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsuite_app.ReadingSystem'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='testsuite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsuite_app.TestSuite'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='epub',
            name='testsuite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsuite_app.TestSuite'),
        ),
        migrations.AddField(
            model_name='category',
            name='testsuite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsuite_app.TestSuite'),
        ),
        migrations.AddField(
            model_name='atmetadata',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsuite_app.Evaluation'),
        ),
    ]
