# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-20 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsuite_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='nothing_tested',
            field=models.BooleanField(default=True),
        ),
    ]
