# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-21 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsuite_app', '0003_auto_20170809_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='long_summary',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='short_summary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
