# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-21 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsuite_app', '0004_evaluation_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='summary',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
